<?php
/**
 * PriceAndAvailabilityResponseServiceresponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product Catalog APIs
 *
 * Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PriceAndAvailabilityResponseServiceresponseTest Class Doc Comment
 *
 * @category    Class
 * @description PriceAndAvailabilityResponseServiceresponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceAndAvailabilityResponseServiceresponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceAndAvailabilityResponseServiceresponse"
     */
    public function testPriceAndAvailabilityResponseServiceresponse()
    {
    }

    /**
     * Test attribute "responsepreamble"
     */
    public function testPropertyResponsepreamble()
    {
    }

    /**
     * Test attribute "priceandstockresponse"
     */
    public function testPropertyPriceandstockresponse()
    {
    }
}
