<?php
/**
 * PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Product Catalog APIs
 *
 * Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemTest Class Doc Comment
 *
 * @category    Class
 * @description PriceAndAvailabilityRequestServicerequestPriceandstockrequestItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceAndAvailabilityRequestServicerequestPriceandstockrequestItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceAndAvailabilityRequestServicerequestPriceandstockrequestItem"
     */
    public function testPriceAndAvailabilityRequestServicerequestPriceandstockrequestItem()
    {
    }

    /**
     * Test attribute "index"
     */
    public function testPropertyIndex()
    {
    }

    /**
     * Test attribute "ingrampartnumber"
     */
    public function testPropertyIngrampartnumber()
    {
    }

    /**
     * Test attribute "vendorpartnumber"
     */
    public function testPropertyVendorpartnumber()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "customerpartnumber"
     */
    public function testPropertyCustomerpartnumber()
    {
    }

    /**
     * Test attribute "warehouseidlist"
     */
    public function testPropertyWarehouseidlist()
    {
    }

    /**
     * Test attribute "extendedvendorpartnumber"
     */
    public function testPropertyExtendedvendorpartnumber()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "enduserid"
     */
    public function testPropertyEnduserid()
    {
    }

    /**
     * Test attribute "govtprogramtype"
     */
    public function testPropertyGovtprogramtype()
    {
    }

    /**
     * Test attribute "govtendusertype"
     */
    public function testPropertyGovtendusertype()
    {
    }

    /**
     * Test attribute "specialbidnumber"
     */
    public function testPropertySpecialbidnumber()
    {
    }
}
